blank_issues_enabled: false
contact_links:
<<<<<<< Updated upstream
  - name: Feature Request
    url: https://github.com/PurpurMC/Purpur/discussions/new
    about: Suggest an idea for Purpur
  - name: Purpur Discord
    url: https://purpurmc.org/discord
    about: If you are having issues with timings or have other minor issues, come join our Discord server for help!
=======
  - name: Purpur Discord
    url: https://purpur.pl3x.net/discord
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
>>>>>>> Stashed changes
